---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: custom-image
# description will be included in the image's metadata
description: A custom Linux based image using blue-build/template.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 44 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - keepassxc
        - niri
        - mpv
        - yt-dlp
        - fuzzel
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-gnome
        - gnome-keyring
        - xwayland-satellite
        - alacritty
        - btop
        - nautilus
        - neovim
        - openrgb
      exclude:
        - akmod-openrgb
  - type: dnf
    repos:
      copr:
        - avengemedia/dms
        - alternateved/keyd
    install:
      packages:
        - dms
        - keyd

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.heroicgameslauncher.hgl
          - com.github.tchx84.Flatseal
          - com.brave.Browser
          - com.valvesoftware.Steam
          - org.gimp.GIMP
          - dev.vencord.Vesktop
          - io.github.kolunmi.Bazaar

      - scope: user # Also add Flathub user repo, but no user packages
  - type: kargs
    kargs:
      - pcie_aspm.policy=performance
      - pcie_port_pm=off

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: systemd
    system:
      enabled:
        - podman.socket
        - openrgb.service
